### ISSUE TITLE
Initial Django Migration Issue

### ISSUE THREAD

**Issue by aidanmcdonagh-sky** [aaugustin/django-sequences#34]
Hi there, I performed a database dump using pg_dump with version 2.7 installed however the new migration file not applied, upon moving to a new instance of my app and restoring the db, the initial migration pops up with:

```
Running migration against app-debug
Traceback (most recent call last):
  File "/app/wholesale/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 117, in handle
    executor.loader.check_consistent_history(connection)
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/loader.py", line 327, in check_consistent_history
    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration table.0025_auto_20190212_1447 is applied before its dependency sequences.0002_alter_sequence_last on database 'default'.
```

In order to get around this, I reverted back to 2.6 and performed the initial migration, in order to use the new version/migration file is there something I need to do? or is this only if you apply the migrations to a new project? and not one with existing positiveIntegerFields?

**Comment by adamchainz** [comment]
I think you’ll need to dig into the history of your migrations more. Why does `table.0025_auto_20190212_1447` depend on `sequences.0002_alter_sequence_last`? And how did your database have the first one applied but not the second? It’s likely that your migrations have been edited after application, or that your database has been modified manually.
